import type { Metadata } from "next";
import { Geist_Mono, Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const ClashDisplayBold = localFont({
  src: "../app/fonts/ClashDisplay-Bold.ttf",
  variable: "--font-clash-display",
});
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${ClashDisplayBold.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
